modLoader="javafml"
loaderVersion="[40,41)"
license="MIT"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees-ArsNouveau/issues"

[[mods]]
modId="dtarsnouveau"
version="${file.jarVersion}"
displayName="Dynamic Trees for Ars Nouveau"

updateJSONURL="https://github.com/DynamicTreesTeam/DynamicTreesVersionInfo/blob/master/Add-ons/ArsNouveau.json?raw=true"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-ars-nouveau"

authors="Max Hyper" #optional
description='''
Compatibility Mod between Dynamic trees and Ars Nouveau
'''

[[dependencies.dtarsnouveau]]
    modId="forge"
    mandatory=true
    versionRange="[40,41)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtarsnouveau]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtarsnouveau]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.0.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtarsnouveau]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[1.0.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtarsnouveau]]
    modId="ars_nouveau"
    mandatory=true
    versionRange="[2.9.0,3.0.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtarsnouveau]]
    modId="ars_elemental"
    mandatory=false
    versionRange="[0.4.9.9,0.5.0.0)"
    ordering="AFTER"
    side="BOTH"

